export enum EntityType {
  FolderPrivate = 1,
  FolderShared,
  FolderDeleted,
  FolderArchive,
  FolderInner,
  NotePrivate,
  NoteShared,
  NoteDeleted,
  NoteArchive,
  NoteInner,
  LabelPrivate,
  LabelDeleted,
  Profile,
  History,
}
