// <auto-generated />
using System;
using System.Collections.Generic;
using Common.DatabaseModels.Models.Files;
using Common.DatabaseModels.Models.History;
using Common.DatabaseModels.Models.History.Contents;
using Common.DatabaseModels.Models.NoteContent.FileContent;
using Common.DatabaseModels.Models.NoteContent.TextContent.TextBlockElements;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WriteContext;

#nullable disable

namespace WriteContext.Migrations
{
    [DbContext(typeof(WriteContextDB))]
    partial class WriteContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Noots")
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.DatabaseModels.Models.Files.AppFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("integer");

                    b.Property<AppFileMetaData>("MetaData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PathNonPhotoContent")
                        .HasColumnType("text");

                    b.Property<string>("PathPhotoBig")
                        .HasColumnType("text");

                    b.Property<string>("PathPhotoMedium")
                        .HasColumnType("text");

                    b.Property<string>("PathPhotoSmall")
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("AppFile", "file");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Files.AppFileUploadInfo", b =>
                {
                    b.Property<Guid>("AppFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LinkedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UnLinkedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppFileId");

                    b.ToTable("AppFileUploadInfo", "file");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Files.FileType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileType", "file");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Audio"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Photo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Document"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Folders.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FolderTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RefTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FolderTypeId");

                    b.HasIndex("RefTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Folder", "folder");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Folders.FoldersNotes", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("NoteId", "FolderId");

                    b.HasIndex("FolderId");

                    b.ToTable("FoldersNotes", "folder");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Folders.FolderType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FolderType", "folder");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Private"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shared"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Archived"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Deleted"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Folders.UsersOnPrivateFolders", b =>
                {
                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessTypeId")
                        .HasColumnType("integer");

                    b.HasKey("FolderId", "UserId");

                    b.HasIndex("AccessTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersOnPrivateFolders", "folder");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.History.CacheNoteHistory", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<HashSet<Guid>>("UsersThatEditIds")
                        .HasColumnType("jsonb");

                    b.HasKey("NoteId");

                    b.ToTable("CacheNoteHistory", "note_history");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.History.NoteSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<ContentSnapshot>("Contents")
                        .HasColumnType("jsonb");

                    b.Property<List<SnapshotNoteLabel>>("Labels")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("NoteTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("RefTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SnapshotTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("NoteTypeId");

                    b.HasIndex("RefTypeId");

                    b.ToTable("NoteSnapshot", "note_history");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.History.SnapshotFileContent", b =>
                {
                    b.Property<Guid>("NoteSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppFileId")
                        .HasColumnType("uuid");

                    b.HasKey("NoteSnapshotId", "AppFileId");

                    b.HasIndex("AppFileId");

                    b.ToTable("SnapshotFileContent", "note_history");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.History.UserNoteSnapshotManyToMany", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NoteSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "NoteSnapshotId");

                    b.HasIndex("NoteSnapshotId");

                    b.ToTable("UserNoteSnapshotManyToMany", "note_history");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Labels.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Label", "label");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Labels.LabelsNotes", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NoteId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("LabelsNotes", "label");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.BaseNoteContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("NoteId");

                    b.ToTable("BaseNoteContent", "note_content");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentType", "note_content");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Text"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Collection"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.FileContent.CollectionNoteAppFile", b =>
                {
                    b.Property<Guid>("CollectionNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppFileId")
                        .HasColumnType("uuid");

                    b.HasKey("CollectionNoteId", "AppFileId");

                    b.HasIndex("AppFileId");

                    b.ToTable("CollectionNoteAppFile", "note_content");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.TextContent.HType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HType", "note_content");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "H1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "H2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "H3"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.TextContent.NoteTextType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NoteTextType", "note_content");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Heading"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dotlist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Numberlist"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Checklist"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoteTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("RefTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UnlockTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NoteTypeId");

                    b.HasIndex("RefTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Note", "note");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.NoteType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NoteType", "note");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Private"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shared"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Archived"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Deleted"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.RelatedNoteUserState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReletatedNoteInnerNoteId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "ReletatedNoteInnerNoteId");

                    b.HasIndex("ReletatedNoteInnerNoteId");

                    b.ToTable("RelatedNoteUserState", "note");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.ReletatedNoteToInnerNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RelatedNoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("RelatedNoteId");

                    b.ToTable("ReletatedNoteToInnerNote", "note");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.UserOnPrivateNotes", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessTypeId")
                        .HasColumnType("integer");

                    b.HasKey("NoteId", "UserId");

                    b.HasIndex("AccessTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOnPrivateNotes", "note");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Plan.BillingPlan", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("MaxSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BillingPlan", "user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxSize = 1048576000L,
                            Name = "Free"
                        },
                        new
                        {
                            Id = 2,
                            MaxSize = 5242880000L,
                            Name = "Standart"
                        },
                        new
                        {
                            Id = 3,
                            MaxSize = 20971520000L,
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Systems.FontSize", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FontSize", "noots_systems");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Big"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Systems.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Language", "noots_systems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Russian"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Systems.RefType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RefType", "noots_systems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Viewer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Editor"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Systems.Theme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Theme", "noots_systems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dark"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Light"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.Background", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("Background", "user");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("boolean");

                    b.Property<string>("TranslateKeyMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserFromId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserToId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserFromId");

                    b.HasIndex("UserToId");

                    b.ToTable("Notification", "user");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.NotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationSetting", "user");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.PersonalizationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentInNoteCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsViewAudioOnNote")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsViewDocumentOnNote")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsViewPhotosOnNote")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsViewTextOnNote")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsViewVideoOnNote")
                        .HasColumnType("boolean");

                    b.Property<int>("NotesInFolderCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("SortedFolderByTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("SortedNoteByTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SortedFolderByTypeId");

                    b.HasIndex("SortedNoteByTypeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PersonalizationSetting", "user");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.SortedByType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SortedByType", "user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AscDate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DescDate"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CustomOrder"
                        });
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BillingPlanId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentBackgroundId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultPhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FontSizeId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ThemeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BillingPlanId");

                    b.HasIndex("CurrentBackgroundId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FontSizeId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ThemeId");

                    b.ToTable("User", "user");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.UserProfilePhoto", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppFileId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("AppFileId");

                    b.ToTable("UserProfilePhoto", "user");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.WS.UserIdentifierConnectionId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserIdentifierConnectionId", "ws");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.FileContent.CollectionNote", b =>
                {
                    b.HasBaseType("Common.DatabaseModels.Models.NoteContent.BaseNoteContent");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("integer");

                    b.Property<CollectionMetadata>("MetaData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasIndex("FileTypeId");

                    b.ToTable("CollectionNote", "note_content");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.TextContent.TextNote", b =>
                {
                    b.HasBaseType("Common.DatabaseModels.Models.NoteContent.BaseNoteContent");

                    b.Property<bool?>("Checked")
                        .HasColumnType("boolean");

                    b.Property<List<TextBlock>>("Contents")
                        .HasColumnType("jsonb");

                    b.Property<int?>("HTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("NoteTextTypeId")
                        .HasColumnType("integer");

                    b.HasIndex("HTypeId");

                    b.HasIndex("NoteTextTypeId");

                    b.ToTable("TextNote", "note_content");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Files.AppFile", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Files.FileType", "FileType")
                        .WithMany("AppFiles")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("Files")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Files.AppFileUploadInfo", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Files.AppFile", "AppFile")
                        .WithOne("AppFileUploadInfo")
                        .HasForeignKey("Common.DatabaseModels.Models.Files.AppFileUploadInfo", "AppFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppFile");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Folders.Folder", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Folders.FolderType", "FolderType")
                        .WithMany("Folders")
                        .HasForeignKey("FolderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Systems.RefType", "RefType")
                        .WithMany("Folders")
                        .HasForeignKey("RefTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("Folders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolderType");

                    b.Navigation("RefType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Folders.FoldersNotes", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Folders.Folder", "Folder")
                        .WithMany("FoldersNotes")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Notes.Note", "Note")
                        .WithMany("FoldersNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Folders.UsersOnPrivateFolders", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Systems.RefType", "AccessType")
                        .WithMany("UsersOnPrivateFolders")
                        .HasForeignKey("AccessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Folders.Folder", "Folder")
                        .WithMany("UsersOnPrivateFolders")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("UsersOnPrivateFolders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessType");

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.History.CacheNoteHistory", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Notes.Note", "Note")
                        .WithOne("CacheNoteHistory")
                        .HasForeignKey("Common.DatabaseModels.Models.History.CacheNoteHistory", "NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.History.NoteSnapshot", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Notes.Note", "Note")
                        .WithMany("History")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Notes.NoteType", "NoteType")
                        .WithMany()
                        .HasForeignKey("NoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Systems.RefType", "RefType")
                        .WithMany()
                        .HasForeignKey("RefTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("NoteType");

                    b.Navigation("RefType");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.History.SnapshotFileContent", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Files.AppFile", "AppFile")
                        .WithMany("SnapshotFileContents")
                        .HasForeignKey("AppFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.History.NoteSnapshot", "NoteSnapshot")
                        .WithMany("SnapshotFileContents")
                        .HasForeignKey("NoteSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppFile");

                    b.Navigation("NoteSnapshot");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.History.UserNoteSnapshotManyToMany", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.History.NoteSnapshot", "NoteSnapshot")
                        .WithMany("UserHistories")
                        .HasForeignKey("NoteSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("UserHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteSnapshot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Labels.Label", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("Labels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Labels.LabelsNotes", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Labels.Label", "Label")
                        .WithMany("LabelsNotes")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Notes.Note", "Note")
                        .WithMany("LabelsNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.BaseNoteContent", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.NoteContent.ContentType", "ContentType")
                        .WithMany("BaseNoteContents")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Notes.Note", "Note")
                        .WithMany("Contents")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.FileContent.CollectionNoteAppFile", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Files.AppFile", "AppFile")
                        .WithMany("PhotosCollectionNoteAppFiles")
                        .HasForeignKey("AppFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.NoteContent.FileContent.CollectionNote", "CollectionNote")
                        .WithMany("CollectionNoteAppFiles")
                        .HasForeignKey("CollectionNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppFile");

                    b.Navigation("CollectionNote");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.Note", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Notes.NoteType", "NoteType")
                        .WithMany("Notes")
                        .HasForeignKey("NoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Systems.RefType", "RefType")
                        .WithMany("Notes")
                        .HasForeignKey("RefTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteType");

                    b.Navigation("RefType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.RelatedNoteUserState", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Notes.ReletatedNoteToInnerNote", "ReletatedNoteInnerNote")
                        .WithMany("RelatedNoteUserStates")
                        .HasForeignKey("ReletatedNoteInnerNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("RelatedNoteUserStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReletatedNoteInnerNote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.ReletatedNoteToInnerNote", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Notes.Note", "Note")
                        .WithMany("ReletatedNoteToInnerNotesFrom")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Notes.Note", "RelatedNote")
                        .WithMany("ReletatedNoteToInnerNotesTo")
                        .HasForeignKey("RelatedNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("RelatedNote");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.UserOnPrivateNotes", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Systems.RefType", "AccessType")
                        .WithMany("UserOnPrivateNotes")
                        .HasForeignKey("AccessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Notes.Note", "Note")
                        .WithMany("UsersOnPrivateNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("UserOnPrivateNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessType");

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.Background", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Files.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("Backgrounds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.Notification", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Users.User", "UserFrom")
                        .WithMany("NotificationsFrom")
                        .HasForeignKey("UserFromId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "UserTo")
                        .WithMany("NotificationsTo")
                        .HasForeignKey("UserToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserFrom");

                    b.Navigation("UserTo");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.NotificationSetting", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithOne("NotificationSettings")
                        .HasForeignKey("Common.DatabaseModels.Models.Users.NotificationSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.PersonalizationSetting", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Users.SortedByType", "SortedFolderByType")
                        .WithMany("PersonalizationSettingsFolders")
                        .HasForeignKey("SortedFolderByTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.SortedByType", "SortedNoteByType")
                        .WithMany("PersonalizationSettingsNotes")
                        .HasForeignKey("SortedNoteByTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithOne("PersonalizationSetting")
                        .HasForeignKey("Common.DatabaseModels.Models.Users.PersonalizationSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SortedFolderByType");

                    b.Navigation("SortedNoteByType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.User", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Plan.BillingPlan", "BillingPlan")
                        .WithMany("Users")
                        .HasForeignKey("BillingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.Background", "CurrentBackground")
                        .WithOne("CurrentUserBackground")
                        .HasForeignKey("Common.DatabaseModels.Models.Users.User", "CurrentBackgroundId");

                    b.HasOne("Common.DatabaseModels.Models.Systems.FontSize", "FontSize")
                        .WithMany("Users")
                        .HasForeignKey("FontSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Systems.Language", "Language")
                        .WithMany("Users")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Systems.Theme", "Theme")
                        .WithMany("Users")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingPlan");

                    b.Navigation("CurrentBackground");

                    b.Navigation("FontSize");

                    b.Navigation("Language");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.UserProfilePhoto", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Files.AppFile", "AppFile")
                        .WithMany("UserProfilePhotos")
                        .HasForeignKey("AppFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithOne("UserProfilePhoto")
                        .HasForeignKey("Common.DatabaseModels.Models.Users.UserProfilePhoto", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.WS.UserIdentifierConnectionId", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Users.User", "User")
                        .WithMany("UserIdentifierConnectionIds")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.FileContent.CollectionNote", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.Files.FileType", "FileType")
                        .WithMany()
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.NoteContent.BaseNoteContent", null)
                        .WithOne()
                        .HasForeignKey("Common.DatabaseModels.Models.NoteContent.FileContent.CollectionNote", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.TextContent.TextNote", b =>
                {
                    b.HasOne("Common.DatabaseModels.Models.NoteContent.TextContent.HType", "HType")
                        .WithMany("TextNotes")
                        .HasForeignKey("HTypeId");

                    b.HasOne("Common.DatabaseModels.Models.NoteContent.BaseNoteContent", null)
                        .WithOne()
                        .HasForeignKey("Common.DatabaseModels.Models.NoteContent.TextContent.TextNote", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.DatabaseModels.Models.NoteContent.TextContent.NoteTextType", "NoteTextType")
                        .WithMany("TextNotes")
                        .HasForeignKey("NoteTextTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HType");

                    b.Navigation("NoteTextType");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Files.AppFile", b =>
                {
                    b.Navigation("AppFileUploadInfo");

                    b.Navigation("PhotosCollectionNoteAppFiles");

                    b.Navigation("SnapshotFileContents");

                    b.Navigation("UserProfilePhotos");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Files.FileType", b =>
                {
                    b.Navigation("AppFiles");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Folders.Folder", b =>
                {
                    b.Navigation("FoldersNotes");

                    b.Navigation("UsersOnPrivateFolders");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Folders.FolderType", b =>
                {
                    b.Navigation("Folders");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.History.NoteSnapshot", b =>
                {
                    b.Navigation("SnapshotFileContents");

                    b.Navigation("UserHistories");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Labels.Label", b =>
                {
                    b.Navigation("LabelsNotes");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.ContentType", b =>
                {
                    b.Navigation("BaseNoteContents");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.TextContent.HType", b =>
                {
                    b.Navigation("TextNotes");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.TextContent.NoteTextType", b =>
                {
                    b.Navigation("TextNotes");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.Note", b =>
                {
                    b.Navigation("CacheNoteHistory");

                    b.Navigation("Contents");

                    b.Navigation("FoldersNotes");

                    b.Navigation("History");

                    b.Navigation("LabelsNotes");

                    b.Navigation("ReletatedNoteToInnerNotesFrom");

                    b.Navigation("ReletatedNoteToInnerNotesTo");

                    b.Navigation("UsersOnPrivateNotes");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.NoteType", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Notes.ReletatedNoteToInnerNote", b =>
                {
                    b.Navigation("RelatedNoteUserStates");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Plan.BillingPlan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Systems.FontSize", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Systems.Language", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Systems.RefType", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Notes");

                    b.Navigation("UserOnPrivateNotes");

                    b.Navigation("UsersOnPrivateFolders");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Systems.Theme", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.Background", b =>
                {
                    b.Navigation("CurrentUserBackground");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.SortedByType", b =>
                {
                    b.Navigation("PersonalizationSettingsFolders");

                    b.Navigation("PersonalizationSettingsNotes");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.Users.User", b =>
                {
                    b.Navigation("Backgrounds");

                    b.Navigation("Files");

                    b.Navigation("Folders");

                    b.Navigation("Labels");

                    b.Navigation("Notes");

                    b.Navigation("NotificationSettings");

                    b.Navigation("NotificationsFrom");

                    b.Navigation("NotificationsTo");

                    b.Navigation("PersonalizationSetting");

                    b.Navigation("RelatedNoteUserStates");

                    b.Navigation("UserHistories");

                    b.Navigation("UserIdentifierConnectionIds");

                    b.Navigation("UserOnPrivateNotes");

                    b.Navigation("UserProfilePhoto");

                    b.Navigation("UsersOnPrivateFolders");
                });

            modelBuilder.Entity("Common.DatabaseModels.Models.NoteContent.FileContent.CollectionNote", b =>
                {
                    b.Navigation("CollectionNoteAppFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
