//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landing.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Landing.Resources.Views.Home.Index.uk", typeof(Index_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш досвід ведення нотаток має бути таким же унікальним, як і ви. За допомогою X Notes налаштуйте інтерфейс на свій смак і створіть робочий простір, який відповідає вашим потребам..
        /// </summary>
        internal static string customization_description {
            get {
                return ResourceManager.GetString("customization-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування користувача.
        /// </summary>
        internal static string customization_title {
            get {
                return ResourceManager.GetString("customization-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Notes дозволяє легко впорядковувати нотатки папками та класифікувати їх ярликами..
        /// </summary>
        internal static string first_block_1 {
            get {
                return ResourceManager.GetString("first-block-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відчуйте інтуїтивно зрозумілий інтерфейс користувача, який надихне вас залишатися організованими та продуктивними..
        /// </summary>
        internal static string first_block_2 {
            get {
                return ResourceManager.GetString("first-block-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завдяки функції одночасного редагування нотаток і папок ви можете співпрацювати з іншими в режимі реального часу, роблячи командну роботу безперебійною та ефективною..
        /// </summary>
        internal static string first_block_3 {
            get {
                return ResourceManager.GetString("first-block-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструйтеся зараз і почніть вивчати всі дивовижні функції X Notes..
        /// </summary>
        internal static string first_block_4 {
            get {
                return ResourceManager.GetString("first-block-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попрощайтеся з безладом і хаосом. За допомогою X Notes ви можете без особливих зусиль упорядкувати свої нотатки в папки, щоб легко знайти те, що вам потрібно, коли вам це потрібно..
        /// </summary>
        internal static string folders_description {
            get {
                return ResourceManager.GetString("folders-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папки.
        /// </summary>
        internal static string folders_title {
            get {
                return ResourceManager.GetString("folders-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберігайте свої нотатки впорядкованими та легкодоступними за допомогою X Notes. Позначайте нотатки ярликами, щоб класифікувати їх і миттєво знаходити те, що вам потрібно..
        /// </summary>
        internal static string labels_description {
            get {
                return ResourceManager.GetString("labels-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ярлики.
        /// </summary>
        internal static string labels_title {
            get {
                return ResourceManager.GetString("labels-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залишайтеся організованими та ефективними з X Notes. Зберігайте всі свої нотатки, будь то текст, фотографії, аудіо, відео чи документи..
        /// </summary>
        internal static string notes_description {
            get {
                return ResourceManager.GetString("notes-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотатки.
        /// </summary>
        internal static string notes_title {
            get {
                return ResourceManager.GetString("notes-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Втомилися перемикати сторінки, щоб знайти потрібну інформацію? За допомогою X Notes ви можете додавати зв&apos;язані нотатки до будь-якого нотатка, щоб ви могли легко отримати доступ до всієї потрібної інформації, не втрачаючи час..
        /// </summary>
        internal static string related_notes_description {
            get {
                return ResourceManager.GetString("related-notes-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зв&apos;язані нотатки.
        /// </summary>
        internal static string related_notes_title {
            get {
                return ResourceManager.GetString("related-notes-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Співпраця є ключем до успіху. За допомогою X Notes ви можете легко ділитися нотатками та папками з друзями чи командою, забезпечуючи безперебійну співпрацю та розробку спільних проектів в реальному часі..
        /// </summary>
        internal static string sharing_description {
            get {
                return ResourceManager.GetString("sharing-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шерінг.
        /// </summary>
        internal static string sharing_title {
            get {
                return ResourceManager.GetString("sharing-title", resourceCulture);
            }
        }
    }
}
