//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landing.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Landing.Resources.Views.Home.Index.en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your note-taking experience should be as unique as you are. With X Notes, customize the interface to your liking and create a workspace that suits your needs..
        /// </summary>
        internal static string customization_description {
            get {
                return ResourceManager.GetString("customization-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customization.
        /// </summary>
        internal static string customization_title {
            get {
                return ResourceManager.GetString("customization-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Notes allows you to effortlessly organize your notes into folders and categorize them with labels..
        /// </summary>
        internal static string first_block_1 {
            get {
                return ResourceManager.GetString("first-block-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience a clean and intuitive user interface that will inspire you to stay organized and productive..
        /// </summary>
        internal static string first_block_2 {
            get {
                return ResourceManager.GetString("first-block-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the feature of simultaneous note and folder editing, you can collaborate with others in real-time, making teamwork seamless and efficient..
        /// </summary>
        internal static string first_block_3 {
            get {
                return ResourceManager.GetString("first-block-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now and start exploring all the amazing functionalities of X Notes..
        /// </summary>
        internal static string first_block_4 {
            get {
                return ResourceManager.GetString("first-block-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say goodbye to clutter and chaos. With X Notes, you can effortlessly organize your notes into folders, making it a breeze to find what you need when you need it..
        /// </summary>
        internal static string folders_description {
            get {
                return ResourceManager.GetString("folders-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string folders_title {
            get {
                return ResourceManager.GetString("folders-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your notes organized and easily accessible with X Notes. Mark notes with labels to categorize them and find what you need in an instant..
        /// </summary>
        internal static string labels_description {
            get {
                return ResourceManager.GetString("labels-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string labels_title {
            get {
                return ResourceManager.GetString("labels-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay organized and efficient with X Notes. Save all your notes, whether they&apos;re text, photos, audio, videos, or documents..
        /// </summary>
        internal static string notes_description {
            get {
                return ResourceManager.GetString("notes-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string notes_title {
            get {
                return ResourceManager.GetString("notes-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tired of flipping through pages to find the information you need? With X Notes, you can add related notes to any note, so you can easily access all the information you need without losing your place..
        /// </summary>
        internal static string related_notes_description {
            get {
                return ResourceManager.GetString("related-notes-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Notes.
        /// </summary>
        internal static string related_notes_title {
            get {
                return ResourceManager.GetString("related-notes-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaboration is key to success. With X Notes, you can easily share notes and folders with your friends or team, enabling seamless collaboration and conquering projects together in real time..
        /// </summary>
        internal static string sharing_description {
            get {
                return ResourceManager.GetString("sharing-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing.
        /// </summary>
        internal static string sharing_title {
            get {
                return ResourceManager.GetString("sharing-title", resourceCulture);
            }
        }
    }
}
